---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed

jobs:
  test-job:
    # check out the repository at the same branch where the Preflight workflow was originally executed
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }} # retrieve the branch name from the event that triggered the workflow_run
      - run: git branch
      - run: env